# Generated by Django 3.2.9 on 2021-11-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True, verbose_name='Artist ID')),
                ('name', models.CharField(max_length=100, verbose_name='Artist Name')),
                ('url', models.URLField(verbose_name='Artist URL')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True, verbose_name='Genre ID')),
                ('name', models.CharField(max_length=50, verbose_name='Genre Name')),
                ('url', models.URLField(verbose_name='Genre URL')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(unique=True, verbose_name='Track ID')),
                ('name', models.CharField(max_length=100, verbose_name='Track Name')),
                ('release_date', models.DateField(blank=True, verbose_name='Release Date')),
                ('kind', models.CharField(max_length=20, verbose_name='Kind')),
                ('url', models.URLField(verbose_name='Track URL')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracks.artist', verbose_name='Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracks.genre', verbose_name='Genre')),
            ],
        ),
    ]
